# Generated by Django 5.2.4 on 2025-07-07 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(10),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=150)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        verbose_name=django.core.validators.RegexValidator(
                            regex="^\\+?1?\\d{9,15}$"
                        ),
                    ),
                ),
            ],
        ),
    ]
