# Generated by Django 5.2.4 on 2025-07-07 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("std", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                verbose_name=django.core.validators.RegexValidator(
                    regex="^\\+?1?\\d{9,15}$"
                ),
            ),
        ),
    ]
